apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: on8vw7e4z-nodejs 
  janus-idp.io/tekton: on8vw7e4z-nodejs
  backstage.io/kubernetes-id: on8vw7e4z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: on8vw7e4z-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  