apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: on8vw7e4z-nodejs
  janus-idp.io/tekton: on8vw7e4z-nodejs
  backstage.io/kubernetes-id: on8vw7e4z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: on8vw7e4z-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
