apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: on8vw7e4z-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: on8vw7e4z-nodejs 
  name: on8vw7e4z-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: on8vw7e4z-nodejs
    weight: 100 
