apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: on8vw7e4z-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: on8vw7e4z-nodejs 
  name: on8vw7e4z-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: on8vw7e4z-nodejs 
